use_frameworks!

platform :ios, '13.0'

target 'SLKit_Example' do
  pod 'SLKit', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'XCGLogger'
  pod 'SnapKit'
  pod 'CocoaAsyncSocket'
  pod 'Toast-Swift'
  pod 'LLNetworkAccessibility-Swift'
  pod 'HandyJSON'
  pod 'KeychainAccess'
  pod 'RealmSwift', '~>10'
  pod 'TZImagePickerController'
  target 'SLKit_Tests' do
    inherit! :search_paths

  end
end
